### ISSUE TITLE
No Module named trellis.utils

### ISSUE THREAD

**Issue by besrabasant** [roots/trellis#1017]
I trying to deploy my setup to my staging server. 

but when I run `ansible-playbook` command, I get the error

`ERROR! Unexpected exception, this is probably a bug: No module name trellis.utils`

On running with `-vvv` option

It throws `ImportError: No module name trellis.utils` at `line 16` in `<project_root>/trellis/lib/trelis/plugins/callback/output.py`

How do I resolve this?

**Comment by roots-ladybug** [comment]
Hi @besrabasant,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
