### ISSUE TITLE
Staging environment should use Staging certificates

### ISSUE THREAD

**Issue by geekodour** [roots/trellis#1066]
I thought trellis took care of my staging certificates using https://letsencrypt.org/docs/staging-environment/

I just hit my rate limits. can we work on this? I'd like to work on it if it's something that can be added.

**Comment by roots-ladybug** [comment]
Hi @geekodour,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by swalkinshaw** [comment]
@geekodour we have a variable which allows you to change it, but it's not done automatically. If you want to look into that it would be appreciated 👍

**Comment by noplanman** [comment]
What about just setting the `letsencrypt_ca` variable by default in the `staging/main.yml` group vars?

```yml
# group_vars/staging/main.yml
letsencrypt_ca: "https://acme-staging-v02.api.letsencrypt.org"
```

**Comment by swalkinshaw** [comment]
Closing this since it's easy to customize as the comment above shows. I'm not sure this should be the default anyway since it's common to have "real" staging servers that require proper certificates.
