### ISSUE TITLE
letsencrypt certificate is expired and not renewed when re-running this playbook

### ISSUE THREAD

**Issue by vesper8** [roots/trellis#1079]
as the title says, I have some certs on a server that are remaining expired even after re-running the playbook. This hasn't happened before. No idea why it's happening now.. is there a way to force the renewal somehow? Anyone else come across this?

**Comment by vesper8** [comment]
The docs also mention a cron job that runs to auto-renew certs, but when I do `sudo crontab -e` or `crontab -e`, I don't see any such job.. could that be the reason?

But wouldn't re-running the playbook cause this renewal script to run in any case?

**Comment by roots-ladybug** [comment]
Hi @vesper8,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by vesper8** [comment]
I was able to fix the issue by setting the ssl to false on affected domains, running the playbook, then changing it back to true and running it again

**Comment by swalkinshaw** [comment]
Thanks for the follow-up. It's hard to say exactly what was happening. But in terms of the cron, I think you actually need to be under the `root` user and not just `sudo`.

**Comment by swalkinshaw** [comment]
You can also see if a cron file named `letsencrypt-certificate-renewal` exists anywhere in `/etc/crond.`  (going by memory)
