### ISSUE TITLE
Remove Prestissimo when Composer 2.x is released

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#1088]
we're currently using https://github.com/hirak/prestissimo to make composer packages download faster and it works great

it looks like it's been added upstream to composer and will be released whenever v2 drops:

https://github.com/composer/composer/pull/5293#issuecomment-458995794

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)

**Comment by furins** [comment]
It seems that the time is come. [Composer 2 is out](https://blog.packagist.com/composer-2-0-is-now-available/) and prestissimo now fails to install (from a trellis vanilla install, PHP forced to 7.4 in order to avoid #1233 ).

```
TASK [composer : Install configured globally-required packages.] ***************
System info:
  Ansible 2.9.13; Vagrant 2.2.10; Darwin
  Trellis version (per changelog): "Allow WP cron intervals to be configurable"
---------------------------------------------------
non-zero return code
Changed current directory to /root/.composer
Do not run Composer as root/super user! See https://getcomposer.org/root for
details


  [InvalidArgumentException]
  Package hirak/prestissimo at version @stable has a PHP requirement
incompatible with your PHP version, PHP extensions and Composer version
```

see also [https://github.com/hirak/prestissimo/issues/233](https://github.com/hirak/prestissimo/issues/233)

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/pull/1247
