### ISSUE TITLE
vagrant up - error during installation

### ISSUE THREAD

**Issue by hartey11** [roots/trellis#1094]
I run `vagrant up` for the first time and get the below error message during installation:

```
==> default: Running provisioner: ansible_local...
    default: Installing Ansible...
    default: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

pip install  --upgrade ansible==2.7.5

Stdout from the command:



Stderr from the command:

bash: line 5: pip: command not found
```

I've disabled FileVault as the documentation says it doesn't work with an encrypted disk - (can I enable this?)

## Versions
MacOS = 10.14.5
Trellis = 1.0.3

**Comment by roots-ladybug** [comment]
Hi @hartey11,
It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).
