### ISSUE TITLE
When running wp algolia reindex it want to connect to my local mysql 

### ISSUE THREAD

**Issue by brambeekman** [roots/trellis#1288]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When running `wp algolia reindex` it wants to connect to my local MySQL is there a way to let wp commands connect to the trellis server database?

**Comment by TangRufus** [comment]
I presume you want to reindex the remote database from local machine.

This is ususally unfavourable because remote server and local machine might have different codebases / settings (`wp options`, PHP constants, etc) / PHP versions.

If you have a strong reason to do it, you might want to:
1. open up remote database for direct connections
2. modify local `.env` to use the remote database
3. `$ wp algolia reindex`

--- 

Important: Before any attempt
- consult the plugin author 
- backup everything
- test on staging server
