### ISSUE TITLE
Personal Data in Commit

### ISSUE THREAD

**Issue by tipf** [roots/trellis#1494]
### Version

Current

### What did you expect to happen?

I did not co-author anything in this repository, so my account should not be linked here.
Further should my private mail not be included in the commit.
So please remove this information. If the maintainer cannot remove it in person, please reach out to GitHub for removing it.

### What actually happens?

@TimmePfeife marked me as a co-author and exposed my personal mail.
I was never asked or contacted in this process.

### Steps to reproduce

Have a look at the commit: https://github.com/roots/trellis/commit/0acbde2ea43f4107a2e4d4c1fc29eec8fa92825f

### Please confirm this isn't a support request.

Yes

**Comment by tipf** [comment]
Hi Scott,
Thanks for your quick response!

I understand that I'm causing a bit of work here, and I'm sorry for that.
On the other hand, this situation is not something I caused in the first place, and it still seems odd that my mail made it into this repo.
So please consider looking into the process. It would at least stop my mail address from being spread to new forks.

By the way, the root cause seems to be this commit:
https://github.com/roots/trellis/pull/1457/commits/4d0ad137328b1cc8f4491d87755da9d60311dfad
I have to say again that I was never involved in this.

The only other option for me would be to file a [Private Information Removal Request](https://docs.github.com/en/site-policy/content-removal-policies/github-private-information-removal-policy#sending-a-private-information-removal-request).
But the process is quite involved and GitHub's policy is a bit vague for me. 


Best Regards
Tim

**Comment by swalkinshaw** [comment]
I've thought about the impact of this and it would cause too much of a disruption. Rewriting Git history means that _every_ single commit since Dec 14th would be changed and get a new commit SHA. This also affects all the releases and tags which point to a specific commit.

I understand you didn't cause this and weren't involved... but neither was I. One person made a seemingly small mistake (just a typo) and there's no easy solution.

I suggest contacting GitHub to see if there's something they can do which wouldn't involve changing our git history.  Sorry about this.

**Comment by tipf** [comment]
Personally, I tend to disagree, because my understanding of data privacy is that the one who violates someone's privacy is obligated to fix it, not the one whose privacy is violated.
However, I can understand that this change is quite involved, and that an email address is not the most sensitive piece of information.

I will try to contact GitHub directly, let's see what happens.
