### ISSUE TITLE
.env should be regenerated based on content 

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#261]
1. Set WP_HOME to example.dev
2. Provision the server
3. WP_HOME in .env is example.dev
4. Set WP_HOME to mysite.dev
5. Provision the server
6. WP_HOME is still example.dev in .env

I would expect this to be regenerated when the values change.

**Comment by louim** [comment]
I agree this is a strange behaviour, but I think it's made that way because the file is synced between the bedrock folder on the vagrant machine and the code folder locally. 

I think we should put a comment in the `.env` file telling users to only change it via the `development` file.  and overwrite it on each provision.

**Comment by austinpray** [comment]
Yeah we should overwrite it each time. Especially seeing that [bedrock gitignores it](https://github.com/roots/bedrock/blob/37bf9ad27b8743c8e05eb8df4ce20b7641070b95/.gitignore#L22)
