### ISSUE TITLE
nginx and php-fpm restart

### ISSUE THREAD

**Issue by balintgaspar** [roots/trellis#359]
Hi!

I provisioned trellis and after I got nginx start page on local machine. So I vagrant ssh into the machine and I saw my site conf was there in the sites-enabled folder, but I always got nginx start page.

After a restarted nginx service and php-fpm everything works fine.

is the ansible restart the services after provision or not?

Thanks, Balint

**Comment by louim** [comment]
The services are reloaded / restarted when related tasks are run by ansible. You can sometime get the problem you described if the nginx and php-fpm tasks run correctly, but the provisioning fail on a subsequent task. Because the provisioning failed, the handlers aren't run. 

On subsequent run, since the task were already ok, ansible see them as already done, and it doesn't call the handler. 

If that was your case, you can always SSH like you did, or you can just `vagrant reload` to restart the machine, which will have the same effect.

**Comment by retlehs** [comment]
please use https://discourse.roots.io/ for questions like this in the future

thx @louim!
