### ISSUE TITLE
Make add user and add ssh keys idempotent

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#409]
For quite a while now my `users | Setup users` task and my `users | Add SSH keys` always report changed. Anyone else seeing this?

**Comment by swalkinshaw** [comment]
Confirmed but there's not much we can do.

"Setup Users" is due to `groups` or `password` usage. See https://github.com/ansible/ansible-modules-core/issues/1118

"Add SSH keys" seems to also be a core bug since we aren't doing much there.

We could potentially set `changed_when` but they are limited.
