### ISSUE TITLE
More hooks?

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/trellis#429]
I really like the idea of the hooks in the deploy process, allowing us to add particular commands at particular points in the deployment process. Would there be any interest in adding additional hooks as part of either the dev or server provisioning process?

Right now, in my local, I added a task to copy down the current remote db after I bring up my local Vagrant instance, but I just modified one of the tasks directly. With hooks, I'd be able to add this somewhere without modifying the core roles.

**Comment by swalkinshaw** [comment]
Hooks in deploys make sense for a few reasons:

* It follows a known pattern like Capistrano (and others)
* It's a more isolated process so there's limited steps where hooks can exist

I don't think I want to open up hooks to the provisioning process because the surface area is huge. For example, if we add a hook in the spot that your use case requires, how do we justify that one over others? How do we decide where or which ones to add?

Trellis is still meant to be forked and customized when necessary. Yeah, it kind of sucks dealing with updates in some cases, but we try and make it extensible through the usual Ansible ways with variables.
