### ISSUE TITLE
Consider using something other than https://diagnostic.opendns.com/myip to get IP

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#437]
I'm not sure this is a super reliable service. I ran into a 503 
![image](https://cloud.githubusercontent.com/assets/2192970/11834410/ce167c6e-a391-11e5-9cb8-201c16b30c58.png)

which caused this

![image](https://cloud.githubusercontent.com/assets/2192970/11834406/c2a26c08-a391-11e5-946c-72760ec7421d.png)

https://github.com/roots/trellis/blob/5d889946e5683b69ac53b1c67cbe06e243568b17/group_vars/all/main.yml

**Comment by QWp6t** [comment]
This might have been what was going on in #434 as well.

As mentioned in that discussion, this worked for me: 
`{{ lookup('pipe', 'curl -4 https://ipinfo.io/ip') }}`

> You are limited to 1,000 API requests per day.

http://ipinfo.io/developers

**Comment by retlehs** [comment]
fwiw i have also seen ipinfo.io become inaccessible in the past (unrelated to the API limitations)

**Comment by coderholic** [comment]
We (http://ipinfo.io) have had 100% uptime ever since we moved to AWS auto-scaling, load balanced servers in 3 different regions (several months ago), and we're hoping to maintain it for a long long time! As a result of the change our latency was also significantly improved, as now your request will automatically get routed to the lowest latency server, be that on the US east or west costs, or in the EU, which are the 3 locations that we currently have servers (more locations coming soon).

**Comment by austinpray** [comment]
@coderholic what's the HTTPS situation? It looks like HTTPS works for free users but on the website it says that you have to pay for HTTPS.

**Comment by coderholic** [comment]
The website works via https, but the API is currently only available via https for subscribers.

```
$ curl https://ipinfo.io/json
SSL access is restricted to paid plans. See http://ipinfo.io/pricing for more details, or contact us via http://ipinfo.io/contact
```

**Comment by austinpray** [comment]
https://ipinfo.io/ip Seems to work fine, however

**Comment by swalkinshaw** [comment]
https://github.com/roots/trellis/pull/440

**Comment by swalkinshaw** [comment]
closed by https://github.com/roots/trellis/pull/444
