### ISSUE TITLE
Trellis deploy fails if any directory names in the root of your repo match the names of directories in the root of your project subtree

### ISSUE THREAD

**Issue by austinpray** [roots/trellis#438]
https://github.com/roots/trellis/blob/2de3e35f43798bd413911e89adde9b5c8e032d1a/roles/deploy/tasks/prepare.yml#L23-L25

can cause a failure

```
stderr: mv: cannot move ‘/srv/www/example.com/releases/20151216074528/site/scripts’ to ‘/srv/www/example.com/releases/20151216074528/scripts’: Directory not empty
```

when your repo structure looks like

![image](https://cloud.githubusercontent.com/assets/2192970/11835139/ebf1af5a-a397-11e5-8feb-b0fc5d66eb12.png)

Basically if the root of your repo contains a `scripts` folder and your subtree `sites` folder has a scripts folder this will fail.

**Comment by swalkinshaw** [comment]
@austinpray proposals? Beyond issuing a warning is there anything we can do?

**Comment by austinpray** [comment]
Yeah I've already fixed this I'll PR soon. 

Instead of current I just have it do

mv {{ deploy_path }} {{ deploy_path }}-temp
mv {{ deploy_path }}-temp/{{ subtree }} {{ deploy_path }}
rm -rf {{ deploy_path }}-temp

**Comment by swalkinshaw** [comment]
What about just replacing a lot of this cloning/moving subtrees with `git archive`?

1. Still clone repo into source dir as usual
2. Instead of copying files to new release path, run `git archive`

`git archive {{ branch }} {{subtree_path}} | tar xf {{ deploy_helper.new_release_path }}`

This is how [Capistrano](https://github.com/capistrano/capistrano/blob/45e851bdc5ed80970a7be90f080f030aa7386190/lib/capistrano/git.rb#L41-L49) does it.

**Comment by swalkinshaw** [comment]
See https://github.com/roots/trellis/pull/451
