### ISSUE TITLE
xdebug-error while provisioning although xdebug is disabled in php.yml

### ISSUE THREAD

**Issue by flurinduerst** [roots/trellis#471]
While provisioning I got the following error on `TASK: [wordpress-install | Install Dependencies with Composer]`: 

`stderr: You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug`

So I disabled xdebug in `group_vars/development/php.yml` => `xdebug_install: false`.

On provisioning, the task for installing Xdebug is shown as 
`TASK: [php | Install Xdebug] ************************************************** skipping: [default]` 
and I still get the error mentioned above. 

Did I miss something or could this be a bug?

**Comment by swalkinshaw** [comment]
It's just a warning actually. We can try and fix it but nothing is actually broken.

**Comment by flurinduerst** [comment]
Well, the error stopped the provisioning. Today the error was gone miraculously (didn't change anything at all.)

**Comment by j0rdn** [comment]
This issue is showing up for me as well.  It looks as though it can only be fixed is by destroying the vm and then running `vagrant up --provision` again (#446) or disabling xdebug . A way to do this without  doing either would be very helpful. The error doesn't seem like it will magically disappear as in @flurinduerst case.
