### ISSUE TITLE
Enable CORS on local dev?

### ISSUE THREAD

**Issue by retlehs** [roots/trellis#480]
on the development environment we should consider bringing in an additional config from the h5bp server configs project:

https://github.com/h5bp/server-configs-nginx/blob/master/h5bp/directive-only/cross-domain-insecure.conf

background info - using browsersync + admin-ajax.php: https://discourse.roots.io/t/browsersync-ajax/5844 (this user isn't using trellis but it's still an issue relevant to trellis)

**Comment by swalkinshaw** [comment]
Was going to add this since it's easy (we already have that file), but on second thought, I don't think we should. CORS is an application concern so if someone needs it in production they can always do a custom include. Just enabling it by default in CORS might not be expected and isn't dev/prod parity.
