### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by mavieth** [roots/trellis#494]
Is PHP 7 necessary? Some plugins do not work well with this version. What would be the best way to change which PHP version is installed?

Thanks!

**Comment by Foxaii** [comment]
You can see what changes were made to incorporate PHP 7 by looking at the commit 1c8cea31f878fc42f0c76ec40ba25fe1f1a9e529.

Reverting the commit may be enough to reinstate PHP 5.6 (ymmv) but it's not something we're able to support.

If the troublesome plugins are just spitting out errors, @retlehs's post about [removing deprecated notices](https://roots.io/disable-php-7-deprecated-notices-from-wordpress-plugins/) is worth a read.

The only other thing I would suggest, wherever possible, is opening issues (good) or PRs (better) to help bring the plugins up-to-date.

**Comment by Telemakhos** [comment]
@Foxaii or @swalkinshaw Because of some plugins and themes I need to run on PHP V5.6 before the maintainers include full PHP7 support...

If I install the repo at the previous commit before PHP 5.6 removal ([this one](https://github.com/roots/trellis/tree/c76089dc276e9878bd7de36ca2d9fc8b4b0a5c2a)).. do you think that bedrock will work without major issues?

**Comment by retlehs** [comment]
it'll work fine. also see https://roots.io/disable-php-7-deprecated-notices-from-wordpress-plugins/
