### ISSUE TITLE
remote-user not asking for root password when determining user

### ISSUE THREAD

**Issue by aried3r** [roots/trellis#574]
**What is the current behavior?**

I'm running `ansible-playbook server.yml -e env=staging --ask-pass` to do an initial provisioning of a server. However, the remote-user role does not respect the password, thus failing and incorrectly failing back to the `admin_user`

**What is the expected or desired behavior?**

remote-user should correctly determine that I can indeed login as root and use that user, using the supplied password.

**Environment**

Ansible version: 2.0.1.0
OS: 10.11.4
Trellis: Current master

**Where did the bug happen? Development or remote servers?**

Remote server.

**Comment by aried3r** [comment]
Maybe as a side note: Unlike DigitalOcean, I cannot deploy a SSH key beforehand on my host (except, of course, manually). But I'd love to have the option to _once_ use `--ask-pass`, then disable root login and password authentication altogether.

I guess I can always add `--ask-pass` myself, once. But I was puzzled to see `--ask-pass` not being honored in the remote-user role and thus thought it's undesired behavior.

**Comment by fullyint** [comment]
Thanks for reporting this. I don't think we noticed this because we assume users have set up SSH keys to connect to their remotes. That's unfortunate that your VPS provider doesn't allow you to load an SSH key at VPS creation time, thus requiring your first connection to use a password.

This is one instance of a broader issue: The remote-user role's [ping command](https://github.com/roots/trellis/blob/ed6c63587adb3ffbdd60f64644470d9f7d81d13d/roles/remote-user/tasks/main.yml#L3) doesn't currently pass all the cli options that users might pass to the primary `ansible-playbook` command.

As a partial solution to that broader issue, #564 added detection for vault-related cli options, passing the options to the remote-user role's ping command. It demonstrates a technique that could be used for other cli options that may be relevant to the ping command, e.g., `--ask-pass`, `--limit`, `--private-key`/`--key-file`, `--user` (should replace `root` in ping command). I'm unsure whether `--ssh-common-args` and `--ssh-extra-args` would also be relevant. I believe these can all be detected in [`cli options`](https://github.com/roots/trellis/blob/ed6c63587adb3ffbdd60f64644470d9f7d81d13d/lib/trellis/plugins/vars/vars.py#L20).

Considering adding support for the above cli options may feel like a hassle and raise the question of whether the remote-user role could be scrapped or replaced. The role has had its share of troubles, but I think they've all been fixed so far (aside from the current issue) and I think the role solves a number of challenges and makes life for users much simpler on the whole (see what the role resolved when it was born in #274). 

My guess is that the solution is to expand the `cli_args_vault` variable to a more general all-encompassing `cli_args` variable.

**Comment by aried3r** [comment]
Thanks for the reply. The way I understand it, even with #564, is that I cannot pass arbitrary options at this point, correct?

I agree, the remote-user role does indeed solve quite a few challenges (I also read all the git history of this file), and I love all the little sanity checks Trellis executes when provisioning. But I think, even though DO is quite appealing, there are many VPS hosters that just send your the root password for the initial setup. Sadly I'm bound to my hoster at this moment (also, I'm not inclined to switch hosters just because I can't pass `--ask-pass` ;)).

I think for the time I'll go with manually adding `--ask-pass` to the remote-user role for initial setup and document that internally somewhere.
I did not (or was unable to) find someone else with that problem, but maybe it's worth documenting somewhere, publicly?

**Comment by fullyint** [comment]
@aried3r would love it if you would test #578 for whether it fixes the issue. No obligation.

**Comment by fullyint** [comment]
Closing. Resolved in #578

**Comment by aried3r** [comment]
Thanks, I'll check it out and report back during the week.
