### ISSUE TITLE
Carriage return in all files prevents deploy script from working properly ( Windows )

### ISSUE THREAD

**Issue by ftrudeau** [roots/trellis#648]
Under Windows host, deploy scripts are unusable from the VM once it is provisioned, because all files are plagued with carriage return :

$ vagrant.exe ssh
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Aug 31 04:12:17 2016 from 10.0.2.2

vagrant@example:~$ cd /vagrant
vagrant@example:/vagrant$ ./deploy.sh
-bash: ./deploy.sh: /bin/bash^M: bad interpreter: No such file or directory

Of course, if files are cleaned manually, everything works as expected. I would however assume that this can be handled by Vagrant automatically ? Am I missing something in the configuration somewhere ?

I'm using latest version of vagrant on windows 10 and latest VirtualBox ( 5.1.4 )

$ vagrant.exe version
Installed Version: 1.8.5
Latest Version: 1.8.5

$ vagrant.exe plugin list
vagrant-bindfs (0.4.9)
vagrant-hostmanager (1.8.5)
vagrant-multi-putty (1.5.0)
vagrant-share (1.1.5, system)
vagrant-winnfsd (1.3.0)

Thanks for any help

**Comment by mikaelwedemeyer** [comment]
You should be using the issue template:
https://github.com/roots/trellis/blob/master/.github/ISSUE_TEMPLATE.md

That said it's due to how git is set by default on windows. You need it set to the following:
git config --global core.autocrlf input

Here is the help article: https://help.github.com/articles/dealing-with-line-endings/#platform-mac
Note, DON'T FOLLOW the windows directions as that is what is causing your issue, git is trying to be helpful.

You can set this on a repo or global level. Note, you need to Remove the repo, set it globally and then clone again, otherwise you'll likely have issues.

**Comment by ftrudeau** [comment]
Thanks for your help.
