### ISSUE TITLE
[development] sshd_permit_root_login

### ISSUE THREAD

**Issue by strarsis** [roots/trellis#788]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/trellis/issues)
- [x] I've read the [docs](https://roots.io/trellis/docs) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/trellis) forums

---

**What is the current behavior?**

With `sshd_permit_root_login` set to false (no ssh root login should be allowed), 
development default group_vars result in error during playboon run:
````
When `sshd_permit_root_login: false`, you must add `sudo` to the `groups` for
admin_user (in `users` hash), and set a password for admin_user in
`vault_users` (in `group_vars/development/vault.yml`). Otherwise Ansible
could lose the ability to run the necessary sudo commands. More info:
> https://roots.io/trellis/docs/security/#admin-user-sudoer-password

fatal: [webdev]: FAILED! => {"assertion": false, "changed": false, "evaluated_to": false, "failed": true}
````
sshd_permit_root_login has to be explicitly set to true in development group vars 
```yml
[...]
sshd_permit_root_login: true
[...]
````
in order to make the ansible playbook run through successfully.

**What is the expected or desired behavior?**

Ansible playbook successfully runs through in development environment.

---

## Bug report

**Please provide steps to reproduce, including full log output:**

- Set `sshd_permit_root_login` to false in the all/ group_vars (this is also the cause of the problem).
- Run the ansible playbook in development environment.

**Please describe your local environment:**

Ansible version: 2.2.1.0

OS: Ubuntu 16.04.2 LTS

Vagrant version: 1.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Comment by fullyint** [comment]
Is there an important reason you are manually running `server.yml` with development, or have you perhaps added the `users` role to `dev.yml`? The suggestion is that you use `dev.yml` for development.

This [validation and error message](https://github.com/roots/trellis/blob/2773baa313a496227eafbe294ca5b30d484c232a/roles/users/tasks/main.yml#L22) is in the `users` role. The `users` role is not in [`dev.yml`](https://github.com/roots/trellis/blob/2773baa313a496227eafbe294ca5b30d484c232a/dev.yml), used for development. The `users` role is only in [`server.yml`](https://github.com/roots/trellis/blob/2773baa313a496227eafbe294ca5b30d484c232a/server.yml#L31) which is intended for staging and production.

**Comment by strarsis** [comment]
@fullyint: I just noticed there is also a comment in the [hosts/development file](https://github.com/roots/trellis/blob/master/hosts/development#L1):
````
# This file is only used for Windows hosts.
[...]
````
But one also wants to use mailhog on Linux, too, hence using development environment/hosts.

**Comment by fullyint** [comment]
Closing because the stated desired behavior of "Ansible playbook successfully runs through in development environment" is achievable by running the playbook intended for the dev VM (`dev.yml`).

Regarding your followup comment, I didn't fully understand if you were stating a problem, a question, or a suggestion. Here are a few comments nonetheless.

Regarding the `hosts/development` file's comment "This file is only used for Windows hosts," that is because in default or basic Trellis operations, Windows is the only host OS that uses the [ansible_local provisioner](https://github.com/roots/trellis/blob/2773baa313a496227eafbe294ca5b30d484c232a/Vagrantfile#L96), and only the ansible_local provisioner uses the `hosts/development` inventory. For users on other host OSs, Vagrant will create and use its own inventory (as mentioned later in the notes in `hosts/development`).

Of course, if you're on a non-Windows host, you're welcome to run `dev.yml` from the host OS using the `dev.yml` playbook and the Vagrant inventory, as mentioned in later in the notes in `hosts/development`. You're also welcome to `vagrant ssh` then run `dev.yml` from the guest VM, where a simple `cd ~/trellis && ansible-playbook dev.yml` should be all you need to provision the VM using a "local connection." That command will end up using `hosts/development` (an example of how it could be used by a non-Windows host) but only because you are issuing a command other than the basic `vagrant up` or `vagrant provision`. So, in other words, feel free to use `hosts/development` however you please.

----

As for your statement that one may want to use mailhog on Linux, I'm not sure which machine you're wanting to provision with mailhog.
- Trellis is designed to provision Ubuntu machines (Vagrant VMs or remote servers) and `vagrant up` will run `dev.yml` and set up mailhog (or you can use steps described above to manually run `dev.yml`).
- If instead you mean you're running Linux as your host machine OS and you want to use the Trellis `dev.yml` playbook and its mailhog role to set up mailhog on your local host machine (i.e., not a Vagrant VM and not a remote server), that's outside the intended use of Trellis, but feel free to adapt the role into your own side project for that purpose.
- Here are [notes](https://discourse.roots.io/t/mailhog-on-staging/8656/6) about (or discouraging) running mailhog on a staging server (vs. the typical dev VM), but that doesn't seem to be at all what you were talking about.
